spring.application.name=platforma
server.port=9091

camunda.rest.url=http://localhost:8080/engine-rest
camunda.bpm.client.base-url=http://localhost:8080/engine-rest
camunda.bpm.client.basic-auth.username=admin
camunda.bpm.client.basic-auth.password=admin

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=82b80c33513474
spring.mail.password=dc84921234a493
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/digitalna-platforma
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/digitalna-platforma/protocol/openid-connect/certs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
# Only needed if your app acts as a 'Client' to get tokens
spring.security.oauth2.client.registration.keycloak.client-id=digitalna-platforma-web-app
spring.security.oauth2.client.registration.keycloak.client-secret=0LL7iHI9mXyu59cAtWwks4ebGeJD8aqB

# Main Database
spring.datasource.main.jdbc-url=jdbc:postgresql://localhost:5432/digitalna-platforma-api
spring.datasource.main.username=postgres
spring.datasource.main.password=root
spring.datasource.main.driver-class-name=org.postgresql.Driver

# Audit Database
spring.datasource.audit.jdbc-url=jdbc:postgresql://localhost:5432/digitalna-platforma-audit
spring.datasource.audit.username=postgres
spring.datasource.audit.password=root
spring.datasource.audit.driver-class-name=org.postgresql.Driver

# Ensure Hibernate actually tries to create the table
spring.jpa.hibernate.ddl-auto=update

# This forces Hibernate to initialize the schema early
spring.jpa.generate-ddl=true

# Show what is happening in the console so you can see the 'CREATE TABLE' command
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG